'use strict';

const TRANSLATIONS = {
  ru: {
    'page-title':      'Кирилл Данюков — Сайт-визитка',
    'hero-name':       'Кирилл Данюков',
    'hero-desc':       'Творческий деятель, КВНщик, блогер, автор медиапроектов и участник общественных инициатив.',
    'hero-since':      'С 2023 года развиваюсь в сфере медиа, видеопроизводства, блогинга и творческих проектов.',
    'scroll-hint':     'листай ниже',
    'section-experience': 'Опыт и достижения',
    'kvn-title':       'КВН',
    'kvn-1':           'Основатель команды КВН «STUD SQUAD»',
    'kvn-2':           'Ранее команда выступала под названием «Орлята»',
    'kvn-3':           'Участие в творческих конкурсах и юмористических мероприятиях',
    'tykni':           'Тыкни!',
    'media-title':     'Медиа и блогинг',
    'media-1':         'Бывший руководитель команды блогеров «Продолжение»',
    'media-2':         'Создание видеороликов, монтаж, работа над авторскими проектами',
    'media-3':         'Производство короткометражных фильмов',
    'startups-title':  'Стартапы и проекты',
    'startups-1':      'Участник развития проекта «Bubble Gum»',
    'startups-2':      'Участие в развитии проекта «BigFoot»',
    'vol-title':       'Волонтёрство',
    'vol-1':           'Участие в волонтёрских развивающих мероприятиях',
    'vol-2':           'Помощь в организации событий и поддержка благотворительных инициатив',
    'vol-3':           'Заместитель руководителя комитета по работе с общежитиями Совета студенческого самоуправления ФГБОУ ВО Мичуринский ГАУ',
    'awards-title':    'Награды',
    'award-1':         'Благодарственное письмо за помощь в организации и проведении Дебюта Первокурсника 2025',
    'award-2':         'Студент года 2025 победитель номинации Творческая личность',
    'who-title':       'Кто я?',
    'blogger-title':   'Блогер',
    'blogger-desc':    'Создаю медиаконтент, работаю с аудиторией, веду блог.',
    'artist-title':    'Артист',
    'artist-desc':     'Участвую в КВН, театральных постановках, творческих событиях.',
    'volunteer-title': 'Волонтёр',
    'volunteer-desc':  'Являюсь волонтёром, участвую в волонтёрских инициативах, поддерживаю развитие сообщества.',
    'host-title':      'Ведущий и организатор',
    'host-desc':       'Организую мероприятия, веду творческие программы, работаю с командами.',
    'works-title':     'Мои работы',
    'video-1': 'Видео 1', 'video-2': 'Видео 2', 'video-3': 'Видео 3', 'video-4': 'Видео 4',
    'video-5': 'Видео 5', 'video-6': 'Видео 6', 'video-7': 'Видео 7', 'video-8': 'Видео 8',
    'orgs-title':      'Волонтёрские организации',
    'orgs-subtitle':   'в которых я состою',
    'contacts-title':  'Контакты',
    'contacts-desc':   'Связаться со мной можно через ВКонтакте.',
    'footer-sign':     'Kirill Danyukov © 2026',
    'easter-label':    'Что это такое?',
    'gamepad-aria':    'Что это такое? — мини-игра',
  },

  en: {
    'page-title':      'Kirill Danyukov — Portfolio',
    'hero-name':       'Kirill Danyukov',
    'hero-desc':       'Creative personality, KVN performer, blogger, author of media projects and participant in public initiatives.',
    'hero-since':      'Since 2023 I have been developing in the fields of media, video production, blogging and creative projects.',
    'scroll-hint':     'scroll down',
    'section-experience': 'Experience & Achievements',
    'kvn-title':       'KVN',
    'kvn-1':           'Founder of the KVN team «STUD SQUAD»',
    'kvn-2':           'Previously the team performed under the name «Orlyata»',
    'kvn-3':           'Participation in creative competitions and humor events',
    'tykni':           'Click me!',
    'media-title':     'Media & Blogging',
    'media-1':         'Former head of the blogger team «Prodolzhenie»',
    'media-2':         'Creating videos, editing, working on original projects',
    'media-3':         'Production of short films',
    'startups-title':  'Startups & Projects',
    'startups-1':      'Participant in the development of the «Bubble Gum» project',
    'startups-2':      'Participation in the development of the «BigFoot» project',
    'vol-title':       'Volunteering',
    'vol-1':           'Participation in volunteer development events',
    'vol-2':           'Assistance in organizing events and support of charitable initiatives',
    'vol-3':           'Deputy Head of the Dormitory Committee of the Student Self-Government Council of Michurinsk State Agrarian University',
    'awards-title':    'Awards',
    'award-1':         'Letter of appreciation for helping organize the First-Year Student Debut 2025',
    'award-2':         'Student of the Year 2025, winner of the Creative Personality nomination',
    'who-title':       'Who am I?',
    'blogger-title':   'Blogger',
    'blogger-desc':    'I create media content, work with audiences, and run a blog.',
    'artist-title':    'Performer',
    'artist-desc':     'I participate in KVN, theatrical performances and creative events.',
    'volunteer-title': 'Volunteer',
    'volunteer-desc':  'I am a volunteer, participate in volunteer initiatives and support community development.',
    'host-title':      'Host & Organizer',
    'host-desc':       'I organize events, host creative programs and work with teams.',
    'works-title':     'My Works',
    'video-1': 'Video 1', 'video-2': 'Video 2', 'video-3': 'Video 3', 'video-4': 'Video 4',
    'video-5': 'Video 5', 'video-6': 'Video 6', 'video-7': 'Video 7', 'video-8': 'Video 8',
    'orgs-title':      'Volunteer Organizations',
    'orgs-subtitle':   'I am a member of',
    'contacts-title':  'Contacts',
    'contacts-desc':   'You can contact me via VKontakte.',
    'footer-sign':     'Kirill Danyukov © 2026',
    'easter-label':    'What is this?',
    'gamepad-aria':    'What is this? — mini-game',
  },

  be: {
    'page-title':      'Кірыл Данюкоў — Сайт-візітка',
    'hero-name':       'Кирилл Данюков',
    'hero-desc':       'Творчы дзеяч, кавэншчык, блогер, аўтар медыяпраектаў і ўдзельнік грамадскіх ініцыятыў.',
    'hero-since':      'З 2023 года развіваюся ў сферы медыя, відэавытворчасці, блогінгу і творчых праектаў.',
    'scroll-hint':     'гартайце ніжэй',
    'section-experience': 'Вопыт і дасягненні',
    'kvn-title':       'КВН',
    'kvn-1':           'Заснавальнік каманды КВН «STUD SQUAD»',
    'kvn-2':           'Раней каманда выступала пад назвай «Арляняты»',
    'kvn-3':           'Удзел у творчых конкурсах і гумарыстычных мерапрыемствах',
    'tykni':           'Тыкні!',
    'media-title':     'Медыя і блогінг',
    'media-1':         'Былы кіраўнік каманды блогераў «Працяг»',
    'media-2':         'Стварэнне відэаролікаў, мантаж, праца над аўтарскімі праектамі',
    'media-3':         'Вытворчасць кароткаметражных фільмаў',
    'startups-title':  'Стартапы і праекты',
    'startups-1':      'Удзельнік развіцця праекта «Bubble Gum»',
    'startups-2':      'Удзел у развіцці праекта «BigFoot»',
    'vol-title':       'Валанцёрства',
    'vol-1':           'Удзел у валанцёрскіх развіваючых мерапрыемствах',
    'vol-2':           'Дапамога ў арганізацыі падзей і падтрымка дабрачынных ініцыятыў',
    'vol-3':           'Намеснік кіраўніка камітэта па рабоце з інтэрнатамі Савета студэнцкага самакіравання ФГБОУ ВО Мічурынскі ДАУ',
    'awards-title':    'Узнагароды',
    'award-1':         'Падзячны ліст за дапамогу ў арганізацыі і правядзенні Дэбюту Першакурсніка 2025',
    'award-2':         'Студэнт года 2025 пераможца намінацыі Творчая асоба',
    'who-title':       'Хто я?',
    'blogger-title':   'Блогер',
    'blogger-desc':    'Ствараю медыякантэнт, працую з аўдыторыяй, вяду блог.',
    'artist-title':    'Артыст',
    'artist-desc':     'Удзельнічаю ў КВН, тэатральных пастаноўках, творчых падзеях.',
    'volunteer-title': 'Валанцёр',
    'volunteer-desc':  'З\'яўляюся валанцёрам, удзельнічаю ў валанцёрскіх ініцыятывах, падтрымліваю развіццё супольнасці.',
    'host-title':      'Вядучы і арганізатар',
    'host-desc':       'Арганізую мерапрыемствы, вяду творчыя праграмы, працую з камандамі.',
    'works-title':     'Мае работы',
    'video-1': 'Відэа 1', 'video-2': 'Відэа 2', 'video-3': 'Відэа 3', 'video-4': 'Відэа 4',
    'video-5': 'Відэа 5', 'video-6': 'Відэа 6', 'video-7': 'Відэа 7', 'video-8': 'Відэа 8',
    'orgs-title':      'Валанцёрскія арганізацыі',
    'orgs-subtitle':   'у якіх я складаюся',
    'contacts-title':  'Кантакты',
    'contacts-desc':   'Звязацца са мной можна праз УКантакце.',
    'footer-sign':     'Kirill Danyukov © 2026',
    'easter-label':    'Што гэта такое?',
    'gamepad-aria':    'Што гэта такое? — міні-гульня',
  },

  uk: {
    'page-title':      'Кирило Данюков — Сайт-візитка',
    'hero-name':       'Кирилл Данюков',
    'hero-desc':       'Творча особистість, кавеенщик, блогер, автор медіапроєктів та учасник громадських ініціатив.',
    'hero-since':      'З 2023 року розвиваюся у сфері медіа, відеовиробництва, блогінгу та творчих проєктів.',
    'scroll-hint':     'гортайте нижче',
    'section-experience': 'Досвід та досягнення',
    'kvn-title':       'КВН',
    'kvn-1':           'Засновник команди КВН «STUD SQUAD»',
    'kvn-2':           'Раніше команда виступала під назвою «Орлята»',
    'kvn-3':           'Участь у творчих конкурсах та гумористичних заходах',
    'tykni':           'Натисни!',
    'media-title':     'Медіа та блогінг',
    'media-1':         'Колишній керівник команди блогерів «Продовження»',
    'media-2':         'Створення відеороликів, монтаж, робота над авторськими проєктами',
    'media-3':         'Виробництво короткометражних фільмів',
    'startups-title':  'Стартапи та проєкти',
    'startups-1':      'Учасник розвитку проєкту «Bubble Gum»',
    'startups-2':      'Участь у розвитку проєкту «BigFoot»',
    'vol-title':       'Волонтерство',
    'vol-1':           'Участь у волонтерських розвиваючих заходах',
    'vol-2':           'Допомога в організації подій та підтримка благодійних ініціатив',
    'vol-3':           'Заступник керівника комітету по роботі з гуртожитками Ради студентського самоврядування ФДБОУ ВО Мічурінський ДАУ',
    'awards-title':    'Нагороди',
    'award-1':         'Подячний лист за допомогу в організації та проведенні Дебюту Першокурсника 2025',
    'award-2':         'Студент року 2025 переможець номінації Творча особистість',
    'who-title':       'Хто я?',
    'blogger-title':   'Блогер',
    'blogger-desc':    'Створюю медіаконтент, працюю з аудиторією, веду блог.',
    'artist-title':    'Артист',
    'artist-desc':     'Беру участь у КВН, театральних постановках, творчих подіях.',
    'volunteer-title': 'Волонтер',
    'volunteer-desc':  'Є волонтером, беру участь у волонтерських ініціативах, підтримую розвиток спільноти.',
    'host-title':      'Ведучий та організатор',
    'host-desc':       'Організовую заходи, веду творчі програми, працюю з командами.',
    'works-title':     'Мої роботи',
    'video-1': 'Відео 1', 'video-2': 'Відео 2', 'video-3': 'Відео 3', 'video-4': 'Відео 4',
    'video-5': 'Відео 5', 'video-6': 'Відео 6', 'video-7': 'Відео 7', 'video-8': 'Відео 8',
    'orgs-title':      'Волонтерські організації',
    'orgs-subtitle':   'в яких я перебуваю',
    'contacts-title':  'Контакти',
    'contacts-desc':   'Зв\'язатися зі мною можна через ВКонтакте.',
    'footer-sign':     'Kirill Danyukov © 2026',
    'easter-label':    'Що це таке?',
    'gamepad-aria':    'Що це таке? — міні-гра',
  },

  kk: {
    'page-title':      'Кирилл Данюков — Портфолио',
    'hero-name':       'Кирилл Данюков',
    'hero-desc':       'Шығармашылық тұлға, КВН ойыншысы, блогер, медиа жобалардың авторы және қоғамдық бастамалардың қатысушысы.',
    'hero-since':      '2023 жылдан бастап медиа, бейнеөндіріс, блогинг және шығармашылық жобалар саласында дамып келемін.',
    'scroll-hint':     'төмен айналдырыңыз',
    'section-experience': 'Тәжірибе және жетістіктер',
    'kvn-title':       'КВН',
    'kvn-1':           '«STUD SQUAD» КВН командасының негізін қалаушы',
    'kvn-2':           'Бұрын команда «Орлята» атымен өнер көрсетті',
    'kvn-3':           'Шығармашылық байқаулар мен юмористік іс-шараларға қатысу',
    'tykni':           'Басыңыз!',
    'media-title':     'Медиа және блогинг',
    'media-1':         '«Продолжение» блогерлер командасының бұрынғы жетекшісі',
    'media-2':         'Бейнероликтер жасау, монтаж, авторлық жобалармен жұмыс',
    'media-3':         'Қысқаметражды фильмдер өндіру',
    'startups-title':  'Стартаптар және жобалар',
    'startups-1':      '«Bubble Gum» жобасын дамытуға қатысушы',
    'startups-2':      '«BigFoot» жобасын дамытуға қатысу',
    'vol-title':       'Волонтерлік',
    'vol-1':           'Волонтерлік дамыту іс-шараларына қатысу',
    'vol-2':           'Іс-шараларды ұйымдастыруға көмек және қайырымдылық бастамаларды қолдау',
    'vol-3':           'Мичуринск МАУ Студенттік өзін-өзі басқару Кеңесінің жатақхана комитеті басшысының орынбасары',
    'awards-title':    'Марапаттар',
    'award-1':         '2025 жылғы бірінші курс студенттерінің дебютін ұйымдастыруға көмегі үшін алғыс хат',
    'award-2':         '2025 жылғы Жыл Студенті, Шығармашылық тұлға номинациясының жеңімпазы',
    'who-title':       'Мен кіммін?',
    'blogger-title':   'Блогер',
    'blogger-desc':    'Медиа контент жасаймын, аудиториямен жұмыс жасаймын, блог жүргіземін.',
    'artist-title':    'Артист',
    'artist-desc':     'КВН-ға, театр қойылымдарына, шығармашылық іс-шараларға қатысамын.',
    'volunteer-title': 'Волонтер',
    'volunteer-desc':  'Волонтермін, волонтерлік бастамаларға қатысамын, қауымдастықтың дамуын қолдаймын.',
    'host-title':      'Жүргізуші және ұйымдастырушы',
    'host-desc':       'Іс-шаралар ұйымдастырамын, шығармашылық бағдарламалар жүргіземін, командалармен жұмыс жасаймын.',
    'works-title':     'Менің жұмыстарым',
    'video-1': 'Бейне 1', 'video-2': 'Бейне 2', 'video-3': 'Бейне 3', 'video-4': 'Бейне 4',
    'video-5': 'Бейне 5', 'video-6': 'Бейне 6', 'video-7': 'Бейне 7', 'video-8': 'Бейне 8',
    'orgs-title':      'Волонтерлік ұйымдар',
    'orgs-subtitle':   'мен мүше болып табылатын',
    'contacts-title':  'Байланыс',
    'contacts-desc':   'Мен ВКонтакте арқылы хабарласуға болады.',
    'footer-sign':     'Kirill Danyukov © 2026',
    'easter-label':    'Бұл не?',
    'gamepad-aria':    'Бұл не? — шағын ойын',
  },

  de: {
    'page-title':      'Kirill Danjukow — Portfolio',
    'hero-name':       'Kirill Danyukov',
    'hero-desc':       'Kreative Persönlichkeit, KVN-Teilnehmer, Blogger, Autor von Medienprojekten und Teilnehmer an öffentlichen Initiativen.',
    'hero-since':      'Seit 2023 entwickle ich mich in den Bereichen Medien, Videoproduktion, Bloggen und kreative Projekte.',
    'scroll-hint':     'nach unten scrollen',
    'section-experience': 'Erfahrung & Erfolge',
    'kvn-title':       'KVN',
    'kvn-1':           'Gründer des KVN-Teams «STUD SQUAD»',
    'kvn-2':           'Früher trat das Team unter dem Namen «Orlyata» auf',
    'kvn-3':           'Teilnahme an kreativen Wettbewerben und Humor-Veranstaltungen',
    'tykni':           'Klick mich!',
    'media-title':     'Medien & Bloggen',
    'media-1':         'Ehemaliger Leiter des Blogger-Teams «Prodolzhenie»',
    'media-2':         'Erstellung von Videos, Schnitt, Arbeit an eigenen Projekten',
    'media-3':         'Produktion von Kurzfilmen',
    'startups-title':  'Startups & Projekte',
    'startups-1':      'Teilnehmer an der Entwicklung des Projekts «Bubble Gum»',
    'startups-2':      'Teilnahme an der Entwicklung des Projekts «BigFoot»',
    'vol-title':       'Ehrenamt',
    'vol-1':           'Teilnahme an ehrenamtlichen Entwicklungsveranstaltungen',
    'vol-2':           'Hilfe bei der Organisation von Veranstaltungen und Unterstützung karitativer Initiativen',
    'vol-3':           'Stellvertretender Vorsitzender des Wohnheim-Ausschusses des Studentischen Selbstverwaltungsrates der Mičurinsk Staatlichen Agrar-Universität',
    'awards-title':    'Auszeichnungen',
    'award-1':         'Dankesschreiben für die Hilfe bei der Organisation des Erstsemester-Debüts 2025',
    'award-2':         'Student des Jahres 2025, Gewinner der Nominierung Kreative Persönlichkeit',
    'who-title':       'Wer bin ich?',
    'blogger-title':   'Blogger',
    'blogger-desc':    'Ich erstelle Medieninhalte, arbeite mit dem Publikum und führe einen Blog.',
    'artist-title':    'Performer',
    'artist-desc':     'Ich nehme an KVN, Theateraufführungen und kreativen Veranstaltungen teil.',
    'volunteer-title': 'Ehrenamtlicher',
    'volunteer-desc':  'Ich bin Ehrenamtlicher, nehme an Freiwilligeninitiativen teil und unterstütze die Gemeinschaftsentwicklung.',
    'host-title':      'Moderator & Organisator',
    'host-desc':       'Ich organisiere Veranstaltungen, moderiere kreative Programme und arbeite mit Teams.',
    'works-title':     'Meine Arbeiten',
    'video-1': 'Video 1', 'video-2': 'Video 2', 'video-3': 'Video 3', 'video-4': 'Video 4',
    'video-5': 'Video 5', 'video-6': 'Video 6', 'video-7': 'Video 7', 'video-8': 'Video 8',
    'orgs-title':      'Ehrenamtliche Organisationen',
    'orgs-subtitle':   'deren Mitglied ich bin',
    'contacts-title':  'Kontakt',
    'contacts-desc':   'Sie können mich über VKontakte kontaktieren.',
    'footer-sign':     'Kirill Danyukov © 2026',
    'easter-label':    'Was ist das?',
    'gamepad-aria':    'Was ist das? — Minispiel',
  },

  fr: {
    'page-title':      'Kirill Danioukov — Portfolio',
    'hero-name':       'Kirill Danyukov',
    'hero-desc':       'Personnalité créative, participant au KVN, blogueur, auteur de projets médiatiques et participant aux initiatives publiques.',
    'hero-since':      'Depuis 2023, je me développe dans les domaines des médias, de la production vidéo, du blogging et des projets créatifs.',
    'scroll-hint':     'défiler vers le bas',
    'section-experience': 'Expérience & Réalisations',
    'kvn-title':       'KVN',
    'kvn-1':           'Fondateur de l\'équipe KVN «STUD SQUAD»',
    'kvn-2':           'Auparavant, l\'équipe se produisait sous le nom «Orlyata»',
    'kvn-3':           'Participation à des concours créatifs et des événements humoristiques',
    'tykni':           'Cliquez!',
    'media-title':     'Médias & Blog',
    'media-1':         'Ancien chef de l\'équipe de blogueurs «Prodolzhenie»',
    'media-2':         'Création de vidéos, montage, travail sur des projets originaux',
    'media-3':         'Production de courts métrages',
    'startups-title':  'Startups & Projets',
    'startups-1':      'Participant au développement du projet «Bubble Gum»',
    'startups-2':      'Participation au développement du projet «BigFoot»',
    'vol-title':       'Bénévolat',
    'vol-1':           'Participation à des événements de développement bénévole',
    'vol-2':           'Aide à l\'organisation d\'événements et soutien aux initiatives caritatives',
    'vol-3':           'Directeur adjoint du comité des résidences du Conseil d\'auto-gouvernance étudiant de l\'Université agraire d\'État de Mitchourinsk',
    'awards-title':    'Prix & Distinctions',
    'award-1':         'Lettre de remerciement pour l\'aide à l\'organisation du Début des Premières Années 2025',
    'award-2':         'Étudiant de l\'année 2025, lauréat de la nomination Personnalité Créative',
    'who-title':       'Qui suis-je ?',
    'blogger-title':   'Blogueur',
    'blogger-desc':    'Je crée du contenu médiatique, travaille avec le public et tiens un blog.',
    'artist-title':    'Artiste',
    'artist-desc':     'Je participe au KVN, à des spectacles théâtraux et à des événements créatifs.',
    'volunteer-title': 'Bénévole',
    'volunteer-desc':  'Je suis bénévole, participe à des initiatives de bénévolat et soutiens le développement communautaire.',
    'host-title':      'Animateur & Organisateur',
    'host-desc':       'J\'organise des événements, anime des programmes créatifs et travaille avec des équipes.',
    'works-title':     'Mes Œuvres',
    'video-1': 'Vidéo 1', 'video-2': 'Vidéo 2', 'video-3': 'Vidéo 3', 'video-4': 'Vidéo 4',
    'video-5': 'Vidéo 5', 'video-6': 'Vidéo 6', 'video-7': 'Vidéo 7', 'video-8': 'Vidéo 8',
    'orgs-title':      'Organisations de bénévolat',
    'orgs-subtitle':   'dont je suis membre',
    'contacts-title':  'Contacts',
    'contacts-desc':   'Vous pouvez me contacter via VKontakte.',
    'footer-sign':     'Kirill Danyukov © 2026',
    'easter-label':    'Qu\'est-ce que c\'est ?',
    'gamepad-aria':    'Qu\'est-ce que c\'est ? — mini-jeu',
  },

  zh: {
    'page-title':      '基里尔·达尼乌科夫 — 个人网站',
    'hero-name':       'Kirill Danyukov',
    'hero-desc':       '创意人士、KVN表演者、博主、媒体项目作者及公共倡议参与者。',
    'hero-since':      '自2023年起，我在媒体、视频制作、博客和创意项目领域不断发展。',
    'scroll-hint':     '向下滑动',
    'section-experience': '经历与成就',
    'kvn-title':       'KVN',
    'kvn-1':           'KVN团队«STUD SQUAD»创始人',
    'kvn-2':           '团队曾以«Орлята»名义演出',
    'kvn-3':           '参与创意比赛和幽默活动',
    'tykni':           '点击！',
    'media-title':     '媒体与博客',
    'media-1':         '博主团队«Продолжение»前负责人',
    'media-2':         '制作视频、剪辑、参与原创项目',
    'media-3':         '短片制作',
    'startups-title':  '创业与项目',
    'startups-1':      '«Bubble Gum»项目发展参与者',
    'startups-2':      '参与«BigFoot»项目发展',
    'vol-title':       '志愿服务',
    'vol-1':           '参与志愿者发展活动',
    'vol-2':           '协助组织活动，支持慈善倡议',
    'vol-3':           '米丘林斯克国立农业大学学生自治委员会宿舍委员会副主任',
    'awards-title':    '荣誉与奖励',
    'award-1':         '因协助组织2025年新生首演而获得感谢信',
    'award-2':         '2025年度学生，创意人物提名获奖者',
    'who-title':       '我是谁？',
    'blogger-title':   '博主',
    'blogger-desc':    '我创作媒体内容，与受众互动，维护博客。',
    'artist-title':    '表演者',
    'artist-desc':     '我参与KVN、戏剧演出和创意活动。',
    'volunteer-title': '志愿者',
    'volunteer-desc':  '我是志愿者，参与志愿倡议，支持社区发展。',
    'host-title':      '主持人与组织者',
    'host-desc':       '我组织活动，主持创意节目，与团队合作。',
    'works-title':     '我的作品',
    'video-1': '视频 1', 'video-2': '视频 2', 'video-3': '视频 3', 'video-4': '视频 4',
    'video-5': '视频 5', 'video-6': '视频 6', 'video-7': '视频 7', 'video-8': '视频 8',
    'orgs-title':      '志愿者组织',
    'orgs-subtitle':   '我所参与的',
    'contacts-title':  '联系方式',
    'contacts-desc':   '您可以通过VKontakte联系我。',
    'footer-sign':     'Kirill Danyukov © 2026',
    'easter-label':    '这是什么？',
    'gamepad-aria':    '这是什么？ — 迷你游戏',
  },

  ko: {
    'page-title':      '키릴 다뉴코프 — 포트폴리오',
    'hero-name':       'Kirill Danyukov',
    'hero-desc':       '창의적 인물, KVN 참가자, 블로거, 미디어 프로젝트 작가 및 공공 이니셔티브 참여자.',
    'hero-since':      '2023년부터 미디어, 영상 제작, 블로깅 및 창의적 프로젝트 분야에서 발전하고 있습니다.',
    'scroll-hint':     '아래로 스크롤',
    'section-experience': '경험 및 성과',
    'kvn-title':       'KVN',
    'kvn-1':           'KVN 팀 «STUD SQUAD» 창립자',
    'kvn-2':           '이전에 팀은 «Орлята»라는 이름으로 활동했습니다',
    'kvn-3':           '창의적 콘테스트 및 유머 행사 참여',
    'tykni':           '클릭!',
    'media-title':     '미디어 및 블로깅',
    'media-1':         '블로거 팀 «Продолжение» 전 리더',
    'media-2':         '동영상 제작, 편집, 자체 프로젝트 작업',
    'media-3':         '단편 영화 제작',
    'startups-title':  '스타트업 및 프로젝트',
    'startups-1':      '«Bubble Gum» 프로젝트 개발 참여자',
    'startups-2':      '«BigFoot» 프로젝트 개발 참여',
    'vol-title':       '자원봉사',
    'vol-1':           '자원봉사 개발 행사 참여',
    'vol-2':           '행사 조직 지원 및 자선 이니셔티브 지원',
    'vol-3':           '미추린스크 국립농업대학교 학생자치위원회 기숙사위원회 부위원장',
    'awards-title':    '수상 및 표창',
    'award-1':         '2025년 신입생 데뷔 행사 조직 지원에 대한 감사장',
    'award-2':         '2025년 올해의 학생, 창의적 인물 부문 수상자',
    'who-title':       '나는 누구인가?',
    'blogger-title':   '블로거',
    'blogger-desc':    '미디어 콘텐츠를 만들고, 청중과 소통하며, 블로그를 운영합니다.',
    'artist-title':    '공연자',
    'artist-desc':     'KVN, 연극 공연 및 창의적 행사에 참여합니다.',
    'volunteer-title': '자원봉사자',
    'volunteer-desc':  '자원봉사자로서 자원봉사 이니셔티브에 참여하고 커뮤니티 발전을 지원합니다.',
    'host-title':      '진행자 및 조직자',
    'host-desc':       '행사를 조직하고, 창의적 프로그램을 진행하며, 팀과 함께 일합니다.',
    'works-title':     '내 작품',
    'video-1': '동영상 1', 'video-2': '동영상 2', 'video-3': '동영상 3', 'video-4': '동영상 4',
    'video-5': '동영상 5', 'video-6': '동영상 6', 'video-7': '동영상 7', 'video-8': '동영상 8',
    'orgs-title':      '자원봉사 단체',
    'orgs-subtitle':   '내가 소속된',
    'contacts-title':  '연락처',
    'contacts-desc':   'VKontakte를 통해 저에게 연락할 수 있습니다.',
    'footer-sign':     'Kirill Danyukov © 2026',
    'easter-label':    '이것은 무엇인가요?',
    'gamepad-aria':    '이것은 무엇인가요? — 미니 게임',
  },

  ja: {
    'page-title':      'キリル・ダニュコフ — ポートフォリオ',
    'hero-name':       'Kirill Danyukov',
    'hero-desc':       'クリエイティブな活動家、KVNパフォーマー、ブロガー、メディアプロジェクトの著者、公共イニシアチブ参加者。',
    'hero-since':      '2023年からメディア、動画制作、ブログ、クリエイティブプロジェクトの分野で活動中。',
    'scroll-hint':     '下にスクロール',
    'section-experience': '経験と実績',
    'kvn-title':       'KVN',
    'kvn-1':           'KVNチーム«STUD SQUAD»創設者',
    'kvn-2':           '以前はチームは«Орлята»という名前で活動していました',
    'kvn-3':           'クリエイティブコンテストとユーモアイベントへの参加',
    'tykni':           'タップ！',
    'media-title':     'メディアとブログ',
    'media-1':         'ブロガーチーム«Продолжение»元リーダー',
    'media-2':         '動画制作、編集、オリジナルプロジェクトへの取り組み',
    'media-3':         '短編映画の制作',
    'startups-title':  'スタートアップとプロジェクト',
    'startups-1':      '«Bubble Gum»プロジェクト開発参加者',
    'startups-2':      '«BigFoot»プロジェクト開発への参加',
    'vol-title':       'ボランティア活動',
    'vol-1':           'ボランティア開発イベントへの参加',
    'vol-2':           'イベント運営支援と慈善イニシアチブのサポート',
    'vol-3':           'ミチュリンスク国立農業大学学生自治評議会寮委員会副委員長',
    'awards-title':    '受賞歴',
    'award-1':         '2025年新入生デビューの組織・運営への支援に対する感謝状',
    'award-2':         '2025年度学生、クリエイティブパーソナリティ部門受賞者',
    'who-title':       '私は誰か？',
    'blogger-title':   'ブロガー',
    'blogger-desc':    'メディアコンテンツを作成し、視聴者と交流し、ブログを運営しています。',
    'artist-title':    'パフォーマー',
    'artist-desc':     'KVN、演劇、クリエイティブイベントに参加しています。',
    'volunteer-title': 'ボランティア',
    'volunteer-desc':  'ボランティアとして活動し、ボランティアイニシアチブに参加し、コミュニティの発展を支援しています。',
    'host-title':      '司会者・主催者',
    'host-desc':       'イベントを企画し、クリエイティブプログラムを司会し、チームと連携します。',
    'works-title':     '私の作品',
    'video-1': '動画 1', 'video-2': '動画 2', 'video-3': '動画 3', 'video-4': '動画 4',
    'video-5': '動画 5', 'video-6': '動画 6', 'video-7': '動画 7', 'video-8': '動画 8',
    'orgs-title':      'ボランティア団体',
    'orgs-subtitle':   '所属している',
    'contacts-title':  '連絡先',
    'contacts-desc':   'VKontakteでご連絡いただけます。',
    'footer-sign':     'Kirill Danyukov © 2026',
    'easter-label':    'これは何ですか？',
    'gamepad-aria':    'これは何ですか？ — ミニゲーム',
  },
  hi: {
    'page-title': 'किरिल डेन्यूकोव - बिजनेस कार्ड वेबसाइट',
    'hero-name':       'Kirill Danyukov\n(किरिल दान्युकोव)',
    'hero-desc': 'रचनात्मक व्यक्ति, केवीएन प्रतिभागी, ब्लॉगर, मीडिया परियोजनाओं के लेखक और सार्वजनिक पहल में भागीदार।',
    'hero-since': '2023 से, मैं मीडिया, वीडियो प्रोडक्शन, ब्लॉगिंग और रचनात्मक परियोजनाओं के क्षेत्र में विकास कर रहा हूं।',
    'scroll-hint': 'नीचे स्क्रॉल करें',
    'section-experience': 'अनुभव और उपलब्धियाँ',
    'kvn-title': 'केवीएन',
    'kvn-1': 'KVN टीम "स्टड स्क्वाड" के संस्थापक',
    'kvn-2': 'पहले, टीम ने "ईगलेट्स" नाम से प्रदर्शन किया था',
    'kvn-3': 'रचनात्मक प्रतियोगिताओं और हास्य कार्यक्रमों में भागीदारी',
    'tykni': 'झांकना!',
    'media-title': 'मीडिया और ब्लॉगिंग',
    'media-1': '"निरंतरता" ब्लॉगिंग टीम के पूर्व नेता',
    'media-2': 'वीडियो निर्माण, संपादन, मूल परियोजनाओं पर काम',
    'media-3': 'लघु फिल्म निर्माण',
    'startups-title': 'स्टार्टअप और प्रोजेक्ट',
    'startups-1': '"बबल गम" परियोजना के विकास में भागीदार',
    'startups-2': 'बिगफुट परियोजना के विकास में भागीदारी',
    'vol-title': 'स्वयं सेवा',
    'vol-1': 'स्वयंसेवी विकास गतिविधियों में भागीदारी',
    'vol-2': 'कार्यक्रमों के आयोजन और धर्मार्थ पहलों का समर्थन करने में सहायता',
    'vol-3': 'संघीय राज्य बजटीय शैक्षिक संस्थान उच्च शिक्षा मिचुरिंस्की राज्य कृषि विश्वविद्यालय के छात्र सरकार परिषद के छात्रावासों के साथ काम करने के लिए समिति के उप प्रमुख',
    'awards-title': 'पुरस्कार',
    'award-1': 'फ्रेशमैन डेब्यू 2025 के आयोजन और संचालन में सहायता के लिए आभार पत्र',
    'award-2': 'स्टूडेंट ऑफ द ईयर 2025 क्रिएटिव पर्सनैलिटी नामांकन का विजेता',
    'who-title': 'मैं कौन हूँ?',
    'blogger-title': 'ब्लॉगर',
    'blogger-desc': 'मैं मीडिया सामग्री बनाता हूं, दर्शकों के साथ काम करता हूं और एक ब्लॉग बनाए रखता हूं।',
    'artist-title': 'कलाकार',
    'artist-desc': 'मैं केवीएन, नाट्य प्रस्तुतियों और रचनात्मक कार्यक्रमों में भाग लेता हूं।',
    'volunteer-title': 'स्वयंसेवक',
    'volunteer-desc': 'मैं एक स्वयंसेवक हूं, स्वयंसेवी पहलों में भाग लेता हूं और सामुदायिक विकास का समर्थन करता हूं।',
    'host-title': 'प्रस्तुतकर्ता एवं आयोजक',
    'host-desc': 'मैं कार्यक्रम आयोजित करता हूं, रचनात्मक कार्यक्रम चलाता हूं, टीमों के साथ काम करता हूं।',
    'works-title': 'मेरे काम',
    'video-1': 'वीडियो 1',
    'video-2': 'वीडियो 2',
    'video-3': 'वीडियो 3',
    'video-4': 'वीडियो 4',
    'video-5': 'वीडियो 5',
    'video-6': 'वीडियो 6',
    'video-7': 'वीडियो 7',
    'video-8': 'वीडियो 8',
    'orgs-title': 'स्वयंसेवी संगठन',
    'orgs-subtitle': 'जिसका मैं सदस्य हूं',
    'contacts-title': 'संपर्क',
    'contacts-desc': 'आप मुझसे VKontakte के माध्यम से संपर्क कर सकते हैं।',
    'footer-sign':     'Kirill Danyukov © 2026',
    'easter-label':    'यह क्या है?',
    'gamepad-aria':    'यह क्या है? — मिनी-गेम',
  },

  ar: {
    'page-title': 'كيريل دانيوكوف – موقع بطاقة العمل',
    'hero-name':       'Kirill Danyukov\n(كيريل دانيوكوف)',
    'hero-desc': 'شخصية إبداعية، مشارك في KVN، مدون، مؤلف مشاريع إعلامية ومشارك في المبادرات العامة.',
    'hero-since': 'منذ عام 2023 وأنا أتطور في مجال الإعلام وإنتاج الفيديو والتدوين والمشاريع الإبداعية.',
    'scroll-hint': 'قم بالتمرير أدناه',
    'section-experience': 'الخبرة والإنجازات',
    'kvn-title': 'كفن',
    'kvn-1': 'مؤسس فريق KVN "STUD SQUAD"',
    'kvn-2': 'وسبق أن أدى الفريق تحت اسم "إيجليتس"',
    'kvn-3': 'المشاركة في المسابقات الإبداعية والفعاليات الفكاهية',
    'tykni': 'كزة!',
    'media-title': 'وسائل الإعلام والمدونات',
    'media-1': 'القائد السابق لفريق التدوين "الاستمرار".',
    'media-2': 'إنشاء الفيديو وتحريره والعمل على المشاريع الأصلية',
    'media-3': 'إنتاج الأفلام القصيرة',
    'startups-title': 'الشركات الناشئة والمشاريع',
    'startups-1': 'مشارك في تطوير مشروع “العلكة الفقاعية”.',
    'startups-2': 'المشاركة في تطوير مشروع BigFoot',
    'vol-title': 'التطوع',
    'vol-1': 'المشاركة في الأنشطة التنموية التطوعية',
    'vol-2': 'المساعدة في تنظيم الفعاليات ودعم المبادرات الخيرية',
    'vol-3': 'نائب رئيس لجنة العمل مع المهاجع التابعة لمجلس الحكومة الطلابية التابع للمؤسسة التعليمية لميزانية الدولة الفيدرالية للتعليم العالي جامعة ميشورينسكي الحكومية الزراعية',
    'awards-title': 'الجوائز',
    'award-1': 'خطاب شكر للمساعدة في تنظيم وإجراء برنامج Freshman Debut 2025',
    'award-2': 'طالب العام 2025 الفائز بترشيح الشخصية المبدعة',
    'who-title': 'من أنا؟',
    'blogger-title': 'مدَّوِن',
    'blogger-desc': 'أقوم بإنشاء محتوى إعلامي، والعمل مع الجماهير، وإدارة مدونة.',
    'artist-title': 'فنان',
    'artist-desc': 'أشارك في KVN والعروض المسرحية والأحداث الإبداعية.',
    'volunteer-title': 'متطوع',
    'volunteer-desc': 'أنا متطوع، أشارك في المبادرات التطوعية، وأدعم تنمية المجتمع.',
    'host-title': 'مقدم ومنظم',
    'host-desc': 'أقوم بتنظيم الأحداث، وتشغيل البرامج الإبداعية، والعمل مع الفرق.',
    'works-title': 'أعمالي',
    'video-1': 'فيديو 1',
    'video-2': 'فيديو 2',
    'video-3': 'فيديو 3',
    'video-4': 'فيديو 4',
    'video-5': 'فيديو 5',
    'video-6': 'فيديو 6',
    'video-7': 'فيديو 7',
    'video-8': 'فيديو 8',
    'orgs-title': 'المنظمات التطوعية',
    'orgs-subtitle': 'الذي أنا عضو فيه',
    'contacts-title': 'اتصالات',
    'contacts-desc': 'يمكنك الاتصال بي عبر فكونتاكتي.',
    'footer-sign':     'Kirill Danyukov © 2026',
    'easter-label':    'ما هذا؟',
    'gamepad-aria':    'ما هذا؟ — لعبة صغيرة',
  },

  pt: {
    'page-title': 'Kirill Danyukov — Site de cartão de visita',
    'hero-name': 'Kirill Danyukov',
    'hero-desc': 'Figura criativa, participante da KVN, blogueira, autora de projetos de mídia e participante de iniciativas públicas.',
    'hero-since': 'Desde 2023 venho desenvolvendo na área de mídia, produção de vídeos, blogs e projetos criativos.',
    'scroll-hint': 'role abaixo',
    'section-experience': 'Experiência e conquistas',
    'kvn-title': 'KVN',
    'kvn-1': 'Fundador da equipe KVN “STUD SQUAD”',
    'kvn-2': 'Anteriormente, a equipe atuava sob o nome de "Eaglets"',
    'kvn-3': 'Participação em concursos criativos e eventos humorísticos',
    'tykni': 'Picar!',
    'media-title': 'Mídia e blogs',
    'media-1': 'Ex-líder da equipe de blogs “Continuação”',
    'media-2': 'Criação de vídeo, edição, trabalho em projetos originais',
    'media-3': 'Produção de curta-metragem',
    'startups-title': 'Startups e projetos',
    'startups-1': 'Participante no desenvolvimento do projeto “Bubble Gum”',
    'startups-2': 'Participação no desenvolvimento do projeto BigFoot',
    'vol-title': 'Voluntariado',
    'vol-1': 'Participação em atividades de desenvolvimento voluntário',
    'vol-2': 'Assistência na organização de eventos e apoio a iniciativas de caridade',
    'vol-3': 'Vice-Chefe da Comissão de Trabalho com Dormitórios do Conselho de Governo Estudantil da Instituição Educacional Orçamentária do Estado Federal de Ensino Superior Universidade Agrária Estadual de Michurinsky',
    'awards-title': 'Prêmios',
    'award-1': 'Carta de agradecimento pela assistência na organização e condução do Freshman Debut 2025',
    'award-2': 'Aluno do Ano 2025 vencedor da indicação de Personalidade Criativa',
    'who-title': 'Quem sou eu?',
    'blogger-title': 'Blogueiro',
    'blogger-desc': 'Eu crio conteúdo de mídia, trabalho com o público e mantenho um blog.',
    'artist-title': 'Artista',
    'artist-desc': 'Participo de KVN, produções teatrais e eventos criativos.',
    'volunteer-title': 'Voluntário',
    'volunteer-desc': 'Sou voluntário, participo de iniciativas voluntárias e apoio o desenvolvimento comunitário.',
    'host-title': 'Apresentador e organizador',
    'host-desc': 'Organizo eventos, dirijo programas criativos, trabalho em equipe.',
    'works-title': 'Meus trabalhos',
    'video-1': 'Vídeo 1',
    'video-2': 'Vídeo 2',
    'video-3': 'Vídeo 3',
    'video-4': 'Vídeo 4',
    'video-5': 'Vídeo 5',
    'video-6': 'Vídeo 6',
    'video-7': 'Vídeo 7',
    'video-8': 'Vídeo 8',
    'orgs-title': 'Organizações voluntárias',
    'orgs-subtitle': 'do qual sou membro',
    'contacts-title': 'Contatos',
    'contacts-desc': 'Você pode entrar em contato comigo via VKontakte.',
    'footer-sign':     'Kirill Danyukov © 2026',
    'easter-label':    'O que é isto?',
    'gamepad-aria':    'O que é isto? — mini-jogo',
  },

  es: {
    'page-title': 'Kirill Danyukov — Sitio web de tarjetas de visita',
    'hero-name': 'Kirill Danyukov',
    'hero-desc': 'Figura creativa, participante de KVN, bloguero, autor de proyectos de medios y participante de iniciativas públicas.',
    'hero-since': 'Desde 2023 me desarrollo en el campo de los medios, la producción de videos, los blogs y los proyectos creativos.',
    'scroll-hint': 'desplácese hacia abajo',
    'section-experience': 'Experiencia y logros',
    'kvn-title': 'kvn',
    'kvn-1': 'Fundador del equipo KVN "STUD SQUAD"',
    'kvn-2': 'Anteriormente, el equipo actuó bajo el nombre de "Aguiluchos".',
    'kvn-3': 'Participación en concursos creativos y eventos humorísticos.',
    'tykni': '¡Meter!',
    'media-title': 'Medios y blogs',
    'media-1': 'Exlíder del equipo de blogs "Continuación"',
    'media-2': 'Creación de vídeo, edición, trabajo en proyectos originales.',
    'media-3': 'producción de cortometrajes',
    'startups-title': 'Startups y proyectos',
    'startups-1': 'Participante en el desarrollo del proyecto “Bubble Gum”',
    'startups-2': 'Participación en el desarrollo del proyecto BigFoot.',
    'vol-title': 'Voluntariado',
    'vol-1': 'Participación en actividades de desarrollo de voluntariado.',
    'vol-2': 'Asistencia en la organización de eventos y apoyo a iniciativas benéficas.',
    'vol-3': 'Jefe Adjunto del Comité de Trabajo con Dormitorios del Consejo de Gobierno Estudiantil de la Institución Educativa Presupuestaria de Educación Superior del Estado Federal Universidad Agraria Estatal Michurinsky',
    'awards-title': 'Premios',
    'award-1': 'Carta de agradecimiento por la asistencia en la organización y realización del Freshman Debut 2025',
    'award-2': 'Estudiante del Año 2025 ganador de la nominación de Personalidad Creativa',
    'who-title': '¿Quién soy yo?',
    'blogger-title': 'Blogger',
    'blogger-desc': 'Creo contenido multimedia, trabajo con audiencias y mantengo un blog.',
    'artist-title': 'Artista',
    'artist-desc': 'Participo en KVN, producciones teatrales y eventos creativos.',
    'volunteer-title': 'Voluntario',
    'volunteer-desc': 'Soy voluntario, participo en iniciativas de voluntariado y apoyo el desarrollo comunitario.',
    'host-title': 'Presentador y organizador',
    'host-desc': 'Organizo eventos, dirijo programas creativos, trabajo en equipos.',
    'works-title': 'mis obras',
    'video-1': 'Vídeo 1',
    'video-2': 'Vídeo 2',
    'video-3': 'Vídeo 3',
    'video-4': 'Vídeo 4',
    'video-5': 'Vídeo 5',
    'video-6': 'Vídeo 6',
    'video-7': 'Vídeo 7',
    'video-8': 'Vídeo 8',
    'orgs-title': 'Organizaciones de voluntariado',
    'orgs-subtitle': 'del cual soy miembro',
    'contacts-title': 'Contactos',
    'contacts-desc': 'Puedes contactarme a través de VKontakte.',
    'footer-sign':     'Kirill Danyukov © 2026',
    'easter-label':    '¿Qué es esto?',
    'gamepad-aria':    '¿Qué es esto? — minijuego',
  },

  it: {
    'page-title': 'Kirill Danyukov — Sito web di biglietti da visita',
    'hero-name': 'Kirill Danjukov',
    'hero-desc': 'Figura creativa, partecipante KVN, blogger, autore di progetti mediatici e partecipante ad iniziative pubbliche.',
    'hero-since': 'Dal 2023 mi occupo di media, produzione video, blogging e progetti creativi.',
    'scroll-hint': 'scorri sotto',
    'section-experience': 'Esperienza e risultati',
    'kvn-title': 'KVN',
    'kvn-1': 'Fondatore del team KVN “STUD SQUAD”',
    'kvn-2': 'In precedenza, la squadra si esibiva sotto il nome di "Eaglets"',
    'kvn-3': 'Partecipazione a concorsi creativi ed eventi umoristici',
    'tykni': 'Colpisci!',
    'media-title': 'Media e blog',
    'media-1': 'Ex leader del team di blog "Continuazione".',
    'media-2': 'Creazione video, editing, lavoro su progetti originali',
    'media-3': 'Produzione di cortometraggi',
    'startups-title': 'Startup e progetti',
    'startups-1': 'Partecipante allo sviluppo del progetto “Bubble Gum”.',
    'startups-2': 'Partecipazione allo sviluppo del progetto BigFoot',
    'vol-title': 'Volontariato',
    'vol-1': 'Partecipazione ad attività di sviluppo del volontariato',
    'vol-2': 'Assistenza nell\'organizzazione di eventi e sostegno ad iniziative di beneficenza',
    'vol-3': 'Vice capo del comitato per il lavoro con i dormitori del Consiglio del governo studentesco dell\'Istituto educativo di bilancio dello Stato federale dell\'istruzione superiore Università agraria statale Michurinsky',
    'awards-title': 'Premi',
    'award-1': 'Lettera di ringraziamento per l\'assistenza nell\'organizzazione e nella conduzione del Freshman Debut 2025',
    'award-2': 'Studente dell\'anno 2025 vincitore della nomination Personalità Creativa',
    'who-title': 'Chi sono io?',
    'blogger-title': 'Blogger',
    'blogger-desc': 'Creo contenuti multimediali, lavoro con il pubblico e gestisco un blog.',
    'artist-title': 'Artista',
    'artist-desc': 'Partecipo a KVN, produzioni teatrali ed eventi creativi.',
    'volunteer-title': 'Volontario',
    'volunteer-desc': 'Sono un volontario, partecipo a iniziative di volontariato e sostengo lo sviluppo della comunità.',
    'host-title': 'Presentatore e organizzatore',
    'host-desc': 'Organizzo eventi, gestisco programmi creativi, lavoro con i team.',
    'works-title': 'I miei lavori',
    'video-1': 'Video1',
    'video-2': 'Video2',
    'video-3': 'video 3',
    'video-4': 'video4',
    'video-5': 'video5',
    'video-6': 'video6',
    'video-7': 'video 7',
    'video-8': 'video8',
    'orgs-title': 'Organizzazioni di volontariato',
    'orgs-subtitle': 'di cui sono membro',
    'contacts-title': 'Contatti',
    'contacts-desc': 'Puoi contattarmi tramite VKontakte.',
    'footer-sign':     'Kirill Danyukov © 2026',
    'easter-label':    'Cos\'è questo?',
    'gamepad-aria':    'Cos\'è questo? — minigioco',
  },

};

// ─── GAME TRANSLATIONS (Fully localized Easter Egg Game) ─────────────────────
const GAME_TRANSLATIONS = {
  ru: {
    'game-aria-label': "Мини-игра Поймай мусор",
    'game-close-aria': "Закрыть игру",
    'game-pause-aria': "Пауза",
    'game-title': "Поймай мусор!",
    'game-start': "Старт",
    'game-records': "Рекорды",
    'game-settings': "Настройки",
    'game-best-score': "Лучший рекорд",
    'game-back': "Назад",
    'game-sound-vol': "Громкость звуков",
    'game-music-vol': "Громкость музыки",
    'game-pause': "Пауза",
    'game-resume': "Продолжить",
    'game-main-menu': "Главное меню",
    'game-over': "Игра окончена",
    'game-your-score': "Ваш счёт:",
    'game-best-score-colon': "Лучший рекорд:",
    'game-new-record': "🏆 НОВЫЙ РЕКОРД!",
    'game-play-again': "Сыграть снова"
  },
  en: {
    'game-aria-label': "Mini-game Catch the Trash",
    'game-close-aria': "Close game",
    'game-pause-aria': "Pause",
    'game-title': "Catch the Trash!",
    'game-start': "Start",
    'game-records': "High Scores",
    'game-settings': "Settings",
    'game-best-score': "Best Score",
    'game-back': "Back",
    'game-sound-vol': "SFX Volume",
    'game-music-vol': "Music Volume",
    'game-pause': "Pause",
    'game-resume': "Resume",
    'game-main-menu': "Main Menu",
    'game-over': "Game Over",
    'game-your-score': "Your Score:",
    'game-best-score-colon': "Best Score:",
    'game-new-record': "🏆 NEW RECORD!",
    'game-play-again': "Play Again"
  },
  be: {
    'game-aria-label': "Міні-гульня Паймай смецце",
    'game-close-aria': "Зачыніць гульню",
    'game-pause-aria': "Паўза",
    'game-title': "Паймай смецце!",
    'game-start': "Старт",
    'game-records': "Рэкорды",
    'game-settings': "Налады",
    'game-best-score': "Лепшы рэкорд",
    'game-back': "Назад",
    'game-sound-vol': "Гучнасць гукаў",
    'game-music-vol': "Гучнасць музыкі",
    'game-pause': "Паўза",
    'game-resume': "Працягнуць",
    'game-main-menu': "Галоўнае меню",
    'game-over': "Гульня скончана",
    'game-your-score': "Ваш рахунак:",
    'game-best-score-colon': "Лепшы рэкорд:",
    'game-new-record': "🏆 НОВЫ Рэкорд!",
    'game-play-again': "Згуляць зноўку"
  },
  uk: {
    'game-aria-label': "Міні-гра Упіймай сміття",
    'game-close-aria': "Закрити гру",
    'game-pause-aria': "Пауза",
    'game-title': "Упіймай сміття!",
    'game-start': "Старт",
    'game-records': "Рекорди",
    'game-settings': "Налаштування",
    'game-best-score': "Найкращий рекорд",
    'game-back': "Назад",
    'game-sound-vol': "Гучність звуків",
    'game-music-vol': "Гучність музики",
    'game-pause': "Пауза",
    'game-resume': "Продовжити",
    'game-main-menu': "Головне меню",
    'game-over': "Гра закінчена",
    'game-your-score': "Ваш рахунок:",
    'game-best-score-colon': "Найкращий рекорд:",
    'game-new-record': "🏆 НОВИЙ РЕКОРД!",
    'game-play-again': "Зіграти знову"
  },
  kk: {
    'game-aria-label': "Қоқысты ұста мини-ойыны",
    'game-close-aria': "Ойынды жабу",
    'game-pause-aria': "Үзіліс",
    'game-title': "Қоқысты ұста!",
    'game-start': "Бастау",
    'game-records': "Рекордтар",
    'game-settings': "Баптаулар",
    'game-best-score': "Үздік рекорд",
    'game-back': "Артқа",
    'game-sound-vol': "Дыбыс деңгейі",
    'game-music-vol': "Музыка деңгейі",
    'game-pause': "Үзіліс",
    'game-resume': "Жалғастыру",
    'game-main-menu': "Басты мәзір",
    'game-over': "Ойын аяқталды",
    'game-your-score': "Сіздің ұпайыңыз:",
    'game-best-score-colon': "Үздік рекорд:",
    'game-new-record': "🏆 ЖАҢА РЕКОРД!",
    'game-play-again': "Қайта ойнау"
  },
  de: {
    'game-aria-label': "Minispiel Fang den Müll",
    'game-close-aria': "Spiel schließen",
    'game-pause-aria': "Pause",
    'game-title': "Fang den Müll!",
    'game-start': "Start",
    'game-records': "Rekorde",
    'game-settings': "Einstellungen",
    'game-best-score': "Bester Rekord",
    'game-back': "Zurück",
    'game-sound-vol': "Effektlautstärke",
    'game-music-vol': "Musiklautstärke",
    'game-pause': "Pause",
    'game-resume': "Fortsetzen",
    'game-main-menu': "Hauptmenü",
    'game-over': "Spiel vorbei",
    'game-your-score': "Dein Ergebnis:",
    'game-best-score-colon': "Bester Rekord:",
    'game-new-record': "🏆 NEUER REKORD!",
    'game-play-again': "Nochmal spielen"
  },
  fr: {
    'game-aria-label': "Mini-jeu Attrape les déchets",
    'game-close-aria': "Fermer le jeu",
    'game-pause-aria': "Pause",
    'game-title': "Attrape les déchets !",
    'game-start': "Commencer",
    'game-records': "Records",
    'game-settings': "Paramètres",
    'game-best-score': "Meilleur score",
    'game-back': "Retour",
    'game-sound-vol': "Volume des sons",
    'game-music-vol': "Volume de la musique",
    'game-pause': "Pause",
    'game-resume': "Continuer",
    'game-main-menu': "Menu principal",
    'game-over': "Jeu terminé",
    'game-your-score': "Votre score :",
    'game-best-score-colon': "Meilleur score :",
    'game-new-record': "🏆 NOUVEAU RECORD !",
    'game-play-again': "Rejouer"
  },
  zh: {
    'game-aria-label': "接住垃圾小游戏",
    'game-close-aria': "关闭游戏",
    'game-pause-aria': "暂停",
    'game-title': "接住垃圾！",
    'game-start': "开始",
    'game-records': "排行榜",
    'game-settings': "设置",
    'game-best-score': "最高纪录",
    'game-back': "返回",
    'game-sound-vol': "音效音量",
    'game-music-vol': "音乐音量",
    'game-pause': "暂停",
    'game-resume': "继续",
    'game-main-menu': "主菜单",
    'game-over': "游戏结束",
    'game-your-score': "你的得分：",
    'game-best-score-colon': "最高纪录：",
    'game-new-record': "🏆 新纪录！",
    'game-play-again': "再玩一次"
  },
  ko: {
    'game-aria-label': "쓰레기 잡기 미니게임",
    'game-close-aria': "게임 닫기",
    'game-pause-aria': "일시정지",
    'game-title': "쓰레기를 잡아라!",
    'game-start': "시작",
    'game-records': "최고 기록",
    'game-settings': "설정",
    'game-best-score': "최고 점수",
    'game-back': "뒤로",
    'game-sound-vol': "효과음 볼륨",
    'game-music-vol': "배경음 볼륨",
    'game-pause': "일시정지",
    'game-resume': "계속하기",
    'game-main-menu': "메인 메뉴",
    'game-over': "게임 오버",
    'game-your-score': "당신의 점수:",
    'game-best-score-colon': "최고 기록:",
    'game-new-record': "🏆 새로운 기록!",
    'game-play-again': "다시 하기"
  },
  ja: {
    'game-aria-label': "ゴミキャッチミニゲーム",
    'game-close-aria': "ゲームを閉じる",
    'game-pause-aria': "一時停止",
    'game-title': "ゴミをキャッチ！",
    'game-start': "スタート",
    'game-records': "ハイスコア",
    'game-settings': "設定",
    'game-best-score': "ベストスコア",
    'game-back': "戻る",
    'game-sound-vol': "効果音音量",
    'game-music-vol': "BGM音量",
    'game-pause': "一時停止",
    'game-resume': "再開",
    'game-main-menu': "メインメニュー",
    'game-over': "ゲームオーバー",
    'game-your-score': "スコア:",
    'game-best-score-colon': "ベストスコア:",
    'game-new-record': "🏆 新記録達成！",
    'game-play-again': "もう一度プレイ"
  },
  hi: {
    'game-aria-label': "कचरा पकड़ो मिनी-गेम",
    'game-close-aria': "खेल बंद करें",
    'game-pause-aria': "विराम",
    'game-title': "कचरा पकड़ो!",
    'game-start': "शुरू करें",
    'game-records': "रिकॉर्ड",
    'game-settings': "सेटिंग्स",
    'game-best-score': "सर्वश्रेष्ठ स्कोर",
    'game-back': "पीछे",
    'game-sound-vol': "ध्वनि वॉल्यूम",
    'game-music-vol': "संगीत वॉल्यूम",
    'game-pause': "विराम",
    'game-resume': "जारी रखें",
    'game-main-menu': "मुख्य मेनू",
    'game-over': "खेल समाप्त",
    'game-your-score': "आपका स्कोर:",
    'game-best-score-colon': "सर्वश्रेष्ठ स्कोर:",
    'game-new-record': "🏆 नया रिकॉर्ड!",
    'game-play-again': "फिर से खेलें"
  },
  ar: {
    'game-aria-label': "لعبة صغيرة التقاط النفايات",
    'game-close-aria': "إغلاق اللعبة",
    'game-pause-aria': "إيقاف مؤقت",
    'game-title': "التقط النفايات!",
    'game-start': "ابدأ",
    'game-records': "الأرقام القياسية",
    'game-settings': "الإعدادات",
    'game-best-score': "أفضل رقم قياسي",
    'game-back': "رجوع",
    'game-sound-vol': "حجم الأصوات",
    'game-music-vol': "حجم الموسيقى",
    'game-pause': "إيقاف مؤقت",
    'game-resume': "استئناف",
    'game-main-menu': "القائمة الرئيسية",
    'game-over': "انتهت اللعبة",
    'game-your-score': "نقاطك:",
    'game-best-score-colon': "أفضل رقم قياسي:",
    'game-new-record': "🏆 رقم قياسي جديد!",
    'game-play-again': "اللعب مجدداً"
  },
  pt: {
    'game-aria-label': "Minijogo Pegue o lixo",
    'game-close-aria': "Fechar jogo",
    'game-pause-aria': "Pausa",
    'game-title': "Pegue o lixo!",
    'game-start': "Iniciar",
    'game-records': "Recordes",
    'game-settings': "Configurações",
    'game-best-score': "Melhor recorde",
    'game-back': "Voltar",
    'game-sound-vol': "Volume dos sons",
    'game-music-vol': "Volume da música",
    'game-pause': "Pausa",
    'game-resume': "Continuar",
    'game-main-menu': "Menu principal",
    'game-over': "Fim de jogo",
    'game-your-score': "Seu recorde:",
    'game-best-score-colon': "Melhor recorde:",
    'game-new-record': "🏆 NOVO RECORDE!",
    'game-play-again': "Jogar novamente"
  },
  es: {
    'game-aria-label': "Minijuego Atrapa la basura",
    'game-close-aria': "Cerrar juego",
    'game-pause-aria': "Pausa",
    'game-title': "¡Atrapa la basura!",
    'game-start': "Comenzar",
    'game-records': "Récords",
    'game-settings': "Configuración",
    'game-best-score': "Mejor récord",
    'game-back': "Volver",
    'game-sound-vol': "Volumen de sonidos",
    'game-music-vol': "Volumen de música",
    'game-pause': "Pausa",
    'game-resume': "Continuar",
    'game-main-menu': "Menú principal",
    'game-over': "Fin de la partida",
    'game-your-score': "Tu puntuación:",
    'game-best-score-colon': "Mejor récord:",
    'game-new-record': "¡🏆 NUEVO RÉCORD!",
    'game-play-again': "Jugar de nuevo"
  },
  it: {
    'game-aria-label': "Minigioco Afferra i rifiuti",
    'game-close-aria': "Chiudi gioco",
    'game-pause-aria': "Pausa",
    'game-title': "Afferra i rifiuti!",
    'game-start': "Inizia",
    'game-records': "Record",
    'game-settings': "Impostazioni",
    'game-best-score': "Miglior record",
    'game-back': "Indietro",
    'game-sound-vol': "Volume suoni",
    'game-music-vol': "Volume musica",
    'game-pause': "Pausa",
    'game-resume': "Continua",
    'game-main-menu': "Menu principale",
    'game-over': "Gioco terminato",
    'game-your-score': "Il tuo punteggio:",
    'game-best-score-colon': "Miglior record:",
    'game-new-record': "🏆 NUOVO RECORD!",
    'game-play-again': "Gioca ancora"
  }
};

// Merge game translations into TRANSLATIONS dynamically
for (const lang in GAME_TRANSLATIONS) {
  if (TRANSLATIONS[lang]) {
    Object.assign(TRANSLATIONS[lang], GAME_TRANSLATIONS[lang]);
  }
}

// Fix hero-name for Hindi and Arabic to remove parenthesized text under Kirill Danyukov
if (TRANSLATIONS.hi) TRANSLATIONS.hi['hero-name'] = 'Kirill Danyukov';
if (TRANSLATIONS.ar) TRANSLATIONS.ar['hero-name'] = 'Kirill Danyukov';

// ─── LANGUAGE SWITCHER LOGIC ─────────────────────────────────────────────────

let currentLang = 'ru';

function applyLang(lang) {
  const dict = TRANSLATIONS[lang];
  if (!dict) return;

  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.dataset.i18n;
    if (dict[key] !== undefined) {
      el.textContent = dict[key];
    }
  });

  document.querySelectorAll('[data-i18n-aria]').forEach(el => {
    const key = el.dataset.i18nAria;
    if (dict[key] !== undefined) {
      el.setAttribute('aria-label', dict[key]);
    }
  });

  document.title = dict['page-title'] || document.title;
  document.documentElement.lang = lang;
  document.documentElement.dir = (lang === 'ar') ? 'rtl' : 'ltr';

  document.querySelectorAll('.lang-option').forEach(btn => {
    btn.classList.toggle('active', btn.dataset.lang === lang);
  });

  currentLang = lang;
  localStorage.setItem('lang', lang);
}

const langBtn      = document.getElementById('langBtn');
const langDropdown = document.getElementById('langDropdown');

langBtn.addEventListener('click', e => {
  e.stopPropagation();
  langDropdown.classList.toggle('open');
});

document.addEventListener('click', () => langDropdown.classList.remove('open'));

langDropdown.addEventListener('click', e => {
  const btn = e.target.closest('.lang-option');
  if (!btn) return;
  applyLang(btn.dataset.lang);
  langDropdown.classList.remove('open');
});

function initLang() {
  const saved = localStorage.getItem('lang');
  if (saved && TRANSLATIONS[saved]) {
    applyLang(saved);
    return;
  }

  // Detect browser language
  const userLangs = navigator.languages || [navigator.language || navigator.userLanguage];
  let matched = null;
  for (let l of userLangs) {
    if (!l) continue;
    l = l.toLowerCase();
    const short = l.split('-')[0];
    if (TRANSLATIONS[l]) {
      matched = l;
      break;
    }
    if (TRANSLATIONS[short]) {
      matched = short;
      break;
    }
  }

  if (matched) {
    applyLang(matched);
  } else {
    applyLang('en'); // Default to English if browser language is not supported
  }
}

initLang();
